import '../styles/globals.css';
import type { Metadata } from 'next';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'SET Environmental',
  description: 'Generated by D Harshil Kumar Reddy',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100 min-h-screen flex flex-col`}>
        <Header />
        <main className="flex-1 overflow-y-auto pt-14">{children}</main>
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
